[package]
name = "smart-led-pio-sr"
version = "0.1.0"
edition = "2021"

[dependencies]
defmt = "0.3.8"
embassy-rp = "0.2.0"
embassy-time = "0.3.2"
fixed = "1.28.0"
pio = "0.2.1"
pio-proc = "0.2.2"
smart-leds = "0.4.0"
